<?php
/**
 * @author Adriaan Knapen <a.d.knapen@protonmail.com>
 * @date 27-2-2017
 */


if (! function_exists('showMessages')) {
    /**
     * Returns the HTML generated from the array of errors generated by our form validator.
     *
     * @param array $messages
     * @param string $pre
     * @param string $post
     * @return string
     */
    function showMessages($messages, $pre = '', $post = '') {
        $result = '';

        foreach ($messages as $type => $typeMessages) {
            $preWithClass = sprintf($pre, $type);
            $postWithClass = sprintf($post, $type);

            foreach ($typeMessages as $message) {
                $result .= $preWithClass . "\n";
                $result .= $message . "\n";
                $result .= $postWithClass . "\n";
            }
        }

        return $result;
    }
}

if (! function_exists('returnTrue')) {
    /**
     * Always returns true.
     *
     * @param mixed $param
     * @return bool
     */
    function returnTrue($param) {
        return true;
    }
}