name: Continuous Integration

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Use Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version-file: .nvmrc
        cache: 'npm'

    - name: Install Node dependencies
      run: npm ci

    - name: Create test environment
      run: docker compose up -d
    
    - name: Wait until test environment is up
      run: npx wait-on@7 http-get://localhost:8080/Install

    - name: Cypress run
      uses: cypress-io/github-action@v6.7.8
      with:
        record: true
      env:
        # pass the Dashboard record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
