name: Publish

on:
  release:
    types: [published]

jobs:
  publish-lisa-php-fpm:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Build and publish lisa-php-fpm
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: addono/lisa-php-fpm
        dockerfile: docker/php-fpm/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true

  publish-lisa-nginx:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Build and publish lisa-nginx
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: addono/lisa-nginx
        dockerfile: docker/nginx/Dockerfile
        context: ./
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
